### ISSUE TITLE
VDC_OUT not connected

### ISSUE THREAD

**Issue by piecol** [Hugoyhu/CYPD3177-Breakout#1]
Hi,

why is this pin not connected in your schematics? the datasheet states this:

> Connect this pin to the output of the PFETs controlled by the VBUS_FET_EN. This is used for
> monitoring the VBUS output. This is the power output of the system.

**Comment by Hugoyhu** [comment]
Good question. I honestly don't remember the thought process I had while designing this. But it does seem to work at least at 9V@1A - sorry I don't have a better answer for you
